import { StyleSheet } from "react-native";
import { WA_DARK, WA_GREEN } from "./constants";

export const s = StyleSheet.create({
  root: { flex: 1, backgroundColor: WA_DARK },
  topBar: { position: "absolute", top: 0, left: 0, right: 0, flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: 10, zIndex: 6 },
  topBtn: { width: 42, height: 42, borderRadius: 21, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(0,0,0,0.35)" },
  postFab: { width: 52, height: 52, borderRadius: 26, backgroundColor: WA_GREEN, alignItems: "center", justifyContent: "center" },
  recPill: { position: "absolute", alignSelf: "center", flexDirection: "row", alignItems: "center", gap: 8, paddingHorizontal: 14, paddingVertical: 8, borderRadius: 999, backgroundColor: "rgba(0,0,0,0.55)", zIndex: 6 },
  recDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: "#E5484D" },
  recText: { color: "#FFFFFF", fontSize: 14, fontWeight: "800", fontVariant: ["tabular-nums"] },
  permBar: { position: "absolute", left: 16, right: 16, flexDirection: "row", alignItems: "center", gap: 10, padding: 12, borderRadius: 14, backgroundColor: "rgba(0,0,0,0.65)", zIndex: 7 },
  permText: { flex: 1, color: "#FFFFFF", fontSize: 12, lineHeight: 17 },
  permBtn: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 999, backgroundColor: "#FFFFFF" },
  permBtnText: { color: "#111114", fontSize: 13, fontWeight: "800" },
  camBottom: { position: "absolute", left: 0, right: 0, bottom: 0, paddingHorizontal: 16, zIndex: 5 },
  camRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 24 },
  sideBtn: { width: 48, height: 48, borderRadius: 24, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(0,0,0,0.35)" },
  shutter: { width: 82, height: 82, borderRadius: 41, borderWidth: 5, borderColor: "#FFFFFF", alignItems: "center", justifyContent: "center" },
  shutterCore: { width: 62, height: 62, borderRadius: 31, backgroundColor: "#FFFFFF" },
  shutterRec: { backgroundColor: "#E5484D", width: 34, height: 34, borderRadius: 8 },
  camHint: { marginTop: 8, textAlign: "center", color: "rgba(255,255,255,0.85)", fontSize: 12, fontWeight: "600" },
  pickRow: { flexDirection: "row", gap: 10, marginTop: 14, paddingBottom: 4 },
  pickCard: { width: 108, borderRadius: 14, backgroundColor: "rgba(255,255,255,0.12)", borderWidth: 1, borderColor: "rgba(255,255,255,0.18)", alignItems: "center", justifyContent: "center", gap: 6, paddingVertical: 14 },
  pickLabel: { color: "#FFFFFF", fontSize: 12, fontWeight: "700" },
  pickGlyph: { color: "#FFFFFF", fontSize: 22, fontWeight: "800" },
  editWrap: { position: "absolute", left: 0, right: 0, bottom: 0, zIndex: 5 },
  editBar: { paddingHorizontal: 12, gap: 10 },
  capRow: { flexDirection: "row", alignItems: "center", gap: 8, backgroundColor: "rgba(0,0,0,0.45)", borderRadius: 24, paddingLeft: 6, paddingRight: 6, paddingVertical: 5 },
  capInput: { flex: 1, color: "#FFFFFF", fontSize: 15, paddingVertical: 8 },
  audPill: { flexDirection: "row", alignItems: "center", gap: 5, maxWidth: 120, paddingHorizontal: 10, paddingVertical: 8, borderRadius: 999, backgroundColor: "rgba(255,255,255,0.16)" },
  audText: { color: "#FFFFFF", fontSize: 11, fontWeight: "700" },
  linkChip: { flexDirection: "row", alignItems: "center", gap: 8, alignSelf: "flex-start", maxWidth: "90%", backgroundColor: "rgba(0,0,0,0.55)", borderRadius: 999, paddingHorizontal: 12, paddingVertical: 8 },
  linkText: { flex: 1, color: "#FFFFFF", fontSize: 13, fontWeight: "600" },
  audioPrev: { borderRadius: 14, backgroundColor: "rgba(0,0,0,0.45)", padding: 12 },
  textTools: { gap: 10 },
  swRow: { flexDirection: "row", gap: 10, paddingVertical: 2 },
  sw: { width: 36, height: 36, borderRadius: 18, borderWidth: 2, borderColor: "transparent" },
  swOn: { borderColor: "#FFFFFF" },
  toolRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  fontRow: { flexDirection: "row", gap: 8 },
  fontBtn: { width: 44, height: 44, borderRadius: 22, backgroundColor: "rgba(0,0,0,0.45)", alignItems: "center", justifyContent: "center" },
  fontOn: { backgroundColor: "rgba(255,255,255,0.9)" },
  fontGlyph: { color: "#FFFFFF", fontSize: 16 },
  doneRoot: { flex: 1, backgroundColor: WA_DARK, paddingHorizontal: 20 },
  doneCard: { borderRadius: 20, backgroundColor: "#111B21", padding: 20, gap: 6, alignItems: "stretch" },
  doneTick: { width: 64, height: 64, borderRadius: 32, backgroundColor: WA_GREEN, alignItems: "center", justifyContent: "center", alignSelf: "center", marginBottom: 8 },
  doneTitle: { color: "#FFFFFF", fontSize: 20, fontWeight: "800", textAlign: "center" },
  doneSub: { color: "rgba(255,255,255,0.65)", fontSize: 13, textAlign: "center", marginBottom: 6 },
});
